name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        working-directory: ./my-app  # Asegúrate de estar en el directorio correcto
        run: npm install

      - name: Ejecutar tests y generar cobertura
        working-directory: ./my-app  # Asegúrate de estar en el directorio correcto
        run: npm test -- --coverage

      - name: Configurar Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Ejecutar análisis de SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        working-directory: ./my-app  # Asegúrate de estar en el directorio correcto
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=AgustinB123_IC-REACT \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Check SonarQube Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: AgustinB123_IC-REACT
        working-directory: ./my-app  # Asegúrate de estar en el directorio correcto
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectKey=AgustinB123_IC-REACT \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.qualitygate.timeout=300
          if [ $? -ne 0 ]; then
            echo "La verificación de la puerta de calidad falló, saliendo..."
            exit 1
          fi

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        working-directory: ./my-app  # Asegúrate de estar en el directorio correcto
        run: npm install

      - name: Construir el proyecto para despliegue
        working-directory: ./my-app  # Asegúrate de estar en el directorio correcto
        run: npm run build

      - name: Desplegar a GitHub Pages
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        working-directory: ./my-app  # Asegúrate de estar en el directorio correcto
        run: |
          git config --global user.email "agustinbrites@gmail.com"
          git config --global user.name "Agustin Brites"
          npx gh-pages -d build -r https://${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/${{ github.repository }}.git
